#!/usr/bin/env node
/**
 * 배포 빌드에 실제로 들어가는 제3자 패키지의 저작권·라이선스 고지를 모아 public/third-party-licenses.txt 로 쓴다.
 * (MIT·OFL 은 "모든 사본에 고지 포함"을 요구한다. 압축 빌드는 @license 주석을 지우므로 따로 싣는다.)
 *
 * - vite build 를 파일 쓰기 없이 돌려, 번들 청크에 렌더된 모듈(트리 셰이킹 뒤)과 CSS 가 가져온 패키지를 모은다.
 *   Vite 가 끼워 넣는 코드(\0vite/modulepreload-polyfill 등)는 vite 패키지로 센다.
 * - 각 패키지 폴더의 LICENSE·COPYING·NOTICE 전문을 싣는다. 라이선스 파일이 없으면 실패한다(고지 누락 방지).
 *   Vite·Rollup 식 "Licenses of bundled dependencies" 절은 그 도구 자체에 묶인 것이라 뺀다.
 * - 결과는 저장소에 커밋한다. 의존성을 바꾸면 다시 실행: node tools/licenses.mjs
 *   --check: 파일을 쓰지 않고, 지금 빌드와 다르면 종료 코드 1(릴리스 전 확인용)
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'vite';

const root = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const outFile = path.join(root, 'public', 'third-party-licenses.txt');
const check = process.argv.includes('--check');

const norm = (p) => p.split(path.sep).join('/').split('\\').join('/');

/** 번들에 렌더된 모듈 id 모으기 */
async function bundledModuleIds() {
  const ids = new Set();
  await build({
    root,
    logLevel: 'silent',
    build: { write: false, emptyOutDir: false, copyPublicDir: false },
    plugins: [{
      name: 'collect-bundled-modules',
      generateBundle(_opts, bundle) {
        for (const item of Object.values(bundle)) {
          if (item.type !== 'chunk') continue;
          for (const id of item.moduleIds ?? Object.keys(item.modules)) ids.add(id);
        }
      },
    }],
  });
  return ids;
}

/** 'a/b/c' → 'a', '@s/a/b' → '@s/a' */
function packageName(spec) {
  const parts = spec.split('/');
  return parts[0].startsWith('@') ? `${parts[0]}/${parts[1]}` : parts[0];
}

/** 모듈 id → 패키지 폴더(node_modules 밖의 우리 코드면 null) */
function packageDirOf(id, unknown) {
  const n = norm(id);
  const i = n.lastIndexOf('node_modules/');
  if (i >= 0) {
    const name = packageName(n.slice(i + 'node_modules/'.length));
    return n.slice(0, i + 'node_modules/'.length) + name;
  }
  if (n.startsWith('\0')) {
    // 번들러가 끼워 넣는 가상 모듈(\0vite/…, \0rolldown/runtime 등): 이름이 같은 설치 패키지의 코드다
    const dir = path.join(root, 'node_modules', packageName(n.slice(1)));
    if (existsSync(path.join(dir, 'package.json'))) return norm(dir);
    unknown.add(n.slice(1));
    return null;
  }
  const rel = norm(path.relative(root, n.split('?')[0]));
  if (!rel.startsWith('src/') && rel !== 'index.html') unknown.add(rel);
  return null;
}

function repoUrl(pkg) {
  const r = typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url;
  const url = r ?? pkg.homepage ?? '';
  return url.replace(/^git\+/, '').replace(/\.git$/, '').replace(/^git:\/\//, 'https://');
}

function readLicenseTexts(dir, name) {
  const files = readdirSync(dir).filter((f) => /^(licen[cs]e|copying|notice)(\.|-|$)/i.test(f)).sort();
  if (!files.length) throw new Error(`[licenses] ${name}: 라이선스 파일이 없습니다(${dir}). 고지 문구를 직접 확인해 이 스크립트에 추가하세요.`);
  return files.map((f) => {
    let text = readFileSync(path.join(dir, f), 'utf8').replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n');
    const cut = text.search(/^#+ *Licenses of bundled dependencies/im);
    if (cut > 0) text = text.slice(0, cut);
    return text.replace(/[ \t]+$/gm, '').trim();
  });
}

const ids = await bundledModuleIds();
const unknown = new Set();
const dirs = new Set();
for (const id of ids) {
  const dir = packageDirOf(id, unknown);
  if (dir) dirs.add(dir);
}
if (unknown.size) {
  // 우리 코드도 알려진 패키지도 아닌 모듈 — 고지가 필요한지 사람이 확인해야 한다
  throw new Error(`[licenses] 출처를 알 수 없는 번들 모듈: ${[...unknown].join(', ')}`);
}

const packages = [...dirs].map((dir) => {
  const pkg = JSON.parse(readFileSync(path.join(dir, 'package.json'), 'utf8'));
  return { name: pkg.name, version: pkg.version, license: pkg.license ?? '(package.json 에 없음)', url: repoUrl(pkg), texts: readLicenseTexts(dir, pkg.name) };
}).sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

const rule = '='.repeat(72);
const lines = [
  'Splash Bash! - third-party software notices',
  rule,
  '',
  'The deployed game bundles the open-source packages listed below. Their',
  'copyright and license notices are reproduced here as their licenses require.',
  "The game's own code, 3D models (generated by the project's Blender scripts)",
  'and sounds (synthesized at runtime) are original to this project.',
  '',
  'Generated from the production build by tools/licenses.mjs - do not edit by hand.',
  '',
  ...packages.map((p) => `  - ${p.name} ${p.version} (${p.license})`),
  '',
];
for (const p of packages) {
  lines.push(rule, `${p.name} ${p.version}`, `License: ${p.license}`);
  if (p.url) lines.push(`Source: ${p.url}`);
  lines.push(rule, '');
  for (const t of p.texts) lines.push(t, '');
}
let out = `${lines.join('\n').trimEnd()}\n`;
// 정적 호스팅이 .txt 에 charset 을 안 붙여도 깨지지 않게: ASCII 가 아니면 UTF-8 BOM 으로 인코딩을 알린다
if (/[^\x00-\x7F]/.test(out)) out = `\uFEFF${out}`;

const rel = norm(path.relative(root, outFile));
if (check) {
  const cur = existsSync(outFile) ? readFileSync(outFile, 'utf8').replace(/\r\n/g, '\n') : '';
  if (cur !== out) {
    console.error(`[licenses] ${rel} 가 지금 빌드와 다릅니다. node tools/licenses.mjs 로 다시 만드세요.`);
    process.exit(1);
  }
  console.log(`[licenses] ${rel} 최신 (${packages.length}개 패키지)`);
} else {
  writeFileSync(outFile, out);
  console.log(`[licenses] ${rel} 작성: ${packages.map((p) => `${p.name}@${p.version}`).join(', ')}`);
}
